// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/movies/:id": {
    params: {
      "id": string;
    };
  };
  "/watchlist": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/movies/:id" | "/watchlist";
  };
  "routes/movies.$id.tsx": {
    id: "routes/movies.$id";
    page: "/movies/:id";
  };
  "routes/watchlist.tsx": {
    id: "routes/watchlist";
    page: "/watchlist";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/movies.$id": typeof import("./app/routes/movies.$id.tsx");
  "routes/watchlist": typeof import("./app/routes/watchlist.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
};